stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/train_FD001.txt
    - src/preprocess.py
    params:
    - rul_cap
    outs:
    - data/processed/train_FD001_processed.csv
